const FETCH_CHECKPOINT_CHANNEL = 'fetchCheckpointChannel';
const FETCH_CHECKPOINT_ADD_CHANNEL = 'fetchCheckpointAddChannel';
const FETCH_CHECKPOINT_REMOVE_CHANNEL = 'fetchCheckpointRemoveChannel';

export {
  FETCH_CHECKPOINT_CHANNEL,
  FETCH_CHECKPOINT_ADD_CHANNEL,
  FETCH_CHECKPOINT_REMOVE_CHANNEL,
};
