const FETCH_CHECKPOINT_EVENTS_CHANNEL = 'fetchCheckpointEvents';
const FETCH_CHECKPOINT_EVENTS_ADD_EVENT_CHANNEL = 'fetchCheckpointEventsAddEvent';
const FETCH_CHECKPOINT_EVENTS_REMOVE_EVENT_CHANNEL = 'fetchCheckpointEventsRemoveEvent';

export {
  FETCH_CHECKPOINT_EVENTS_CHANNEL,
  FETCH_CHECKPOINT_EVENTS_ADD_EVENT_CHANNEL,
  FETCH_CHECKPOINT_EVENTS_REMOVE_EVENT_CHANNEL,
};
