const FETCH_CHECKPOINT_ROWS_COUNT_CHANNEL = 'fetchCheckpointRowsCountChannel';
const ADD_ROW_CHANNEL = 'addRowChannel';
const REMOVE_ROW_CHANNEL = 'removeRowChannel';
const FETCH_CHECKPOINT_BY_PAGE_CHANNEL = 'fetchCheckpointByPageChannel';

export {
  FETCH_CHECKPOINT_ROWS_COUNT_CHANNEL,
  ADD_ROW_CHANNEL,
  REMOVE_ROW_CHANNEL,
  FETCH_CHECKPOINT_BY_PAGE_CHANNEL,
};
